name = "solar-and-sundry-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"
kv_namespaces = [
  { binding = "SOLAR_AND_SUNDRY", id = "1ba6e4eff0cf4851aa5ac1b826b94eb1", preview_id = "d5a1903ae78c4ad8b4bcaa72bab92f9c" }
]

[vars]
WORKERS_RS_VERSION = "0.0.11"

[build]
command = "cargo install -q worker-build --version 0.0.9 && worker-build --release"
